name: Frontend CI

on:
  push:
    branches: [ ci_pipeline ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: ./rate-my-club

    strategy:
      matrix:
        os: [self-hosted]
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: | 
          npm ci
      - name: Run build
        run: npm run build --if-present
      - name: Run tests
        run: npm test
